MDAnalysis/cookiecutter-mdakit

{{cookiecutter.repo_name}}/AUTHORS.md, {{cookiecutter.repo_name}}/CHANGELOG.md, {{cookiecutter.repo_name}}/CONTRIBUTING.md
This PR adds the files we are accustomed to in https://github.com/MDAnalysis/mdanalysis but are not in MolSSI's cookiecutter. However, I have made the following changes:
* they're all Markdown
* The "rules" are commented so only visible to people editing the file
* I adapted the "Keep a Changelog" sections and made the contributors an explicit section, instead of hewing more closely to MDAnalysis's current format
My reasoning for this is that Markdown is just much easier to work with than rst; you can preview it and type directly into GitHub, for example. Having some kind of formatting also makes it easier to read in GitHub instead of just a straight text file. To get authors for the documentation might require a little more fancy regex, but not by much.
Please see examples at:
* …
=> Add AUTHORS, CHANGELOG, CONTRIBUTING

{{cookiecutter.repo_name}}/CODE_OF_CONDUCT.md
I have essentially replaced the MolSSI's code of conduct with ours. Minor changes have been made to make it more general, including:
* Taking out the parts that invite people to contact us via mailing list or the anonymous form
* Taking out the parts referring to specific roles in the community (e.g. founders, developers, mentors) and spaces (e.g. Discord, mailing list, etc)
Instead, I kept the sections MolSSI has on scope and enforcement:
```
This Code of Conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community. Examples of
representing a project or community include using an official project e-mail
address, posting via an official social media account, or acting as an
appointed representative at an online or offline …
```
=> Update code of conduct

.github/workflows/gh-ci.yaml
Tiny thing, was just looking at the usage of the python version setting up, turns out one of the steps as using the wrong environment variable.
=> stable-python-version to python-version

.github/workflows/gh-ci.yaml, AUTHORS.md
- Workaround proposed in https://github.com/conda-incubator/setup-miniconda/issues/274#issue-1531425010
- Set to use mamba over conda
=> Patch CI package management

.github/workflows/gh-ci.yaml, CHANGELOG.md, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
Fixes #37 
- The project template CI was changed to use Mambaforge so it doesn't fail by default
PR Checklist
------------
=> Use Mambaforge in the generated project

CHANGELOG.md, README.md
Fixes #33
- Add "2+" after cookiecutter in README
PR Checklist
------------
=> Add cookiecutter 2+ to README

docs/requirements.yaml, docs/source/conf.py, docs/source/index.rst, docs/source/usage.rst, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml, {{cookiecutter.repo_name}}/docs/requirements.yaml, {{cookiecutter.repo_name}}/docs/source/api.rst, {{cookiecutter.repo_name}}/docs/source/conf.py
Fixes #56
- Pin sphinx < 7
- Minor fixes to links and complaints about the example repo
PR Checklist
------------
=> Try fixing docs

CHANGELOG.md, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
Fixes #59
- Removed Python 3.8 from the cookiecutter build matrix
=> Remove Python 3.8 from cookiecutter build matrix

AUTHORS.md, CHANGELOG.md, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
Fixes #54
- add condition on running codecov to exclude CRON CI
PR Checklist
------------
- n/a Tests?
- n/a Docs?
=> template CI workflow: do not run codecov coverage in CRON CI

CHANGELOG.md, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
Fixes #68 
- Added Python 3.11 to the cookiecutter build matrix
=> Adding Python 3.11 to build matrix

CHANGELOG.md, {{cookiecutter.repo_name}}/docs/source/conf.py
`sys.path` was modified after the attempted import. As far as I'm aware, there is no reason for this ordering of statements. Fixes #60
=> sys.path needs to be modified before any imports

AUTHORS.md, CHANGELOG.md, {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/analysis/{{cookiecutter.template_analysis_class.lower()}}.py
Shouldn't `**kwargs` be propagated to AnalysisBase? Since users might adapt the provided code snippet, it might be worth adding.
- Propagate kwargs to AnalysisBase
PR Checklist
------------
=> Propagate kwargs to AnalysisBase

CHANGELOG.md, {{cookiecutter.repo_name}}/pyproject.toml, {{cookiecutter.repo_name}}/setup.py
- Bump minimum Python version in line with CI
PR #62 removed Python 3.8 from the cookiecutter build matrix. I think the minimum Python version should be updated too (so that all supported versions are tested). Users can of course change this if they want to, pinning the version of MDAnalysis accordingly.
PR Checklist
------------
=> Bump minimum Python version in line with CI

.github/workflows/gh-ci.yaml, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
This would avoid the need to manually update Python versions as MDAnalysis develop updates, effectively removing a very simple but painful failure point.
- switch to using new mdanalysis-compatible-python action
- extra Python matrix from this instead
PR Checklist
------------
=> Use a dynamic matrix definition in CI

{{cookiecutter.repo_name}}/docs/source/conf.py
Follow-up from https://github.com/MDAnalysis/mdaencore/pull/18 and https://github.com/MDAnalysis/mdaencore/issues/16
The old intersphinx_mapping use is deprecated, this switches to the new dict + tuple approach.
=> fix intersphinx_mapping

{{cookiecutter.repo_name}}/docs/source/conf.py
- Fixes #81
PR Checklist
------------
=> Mock import of tests module from package

{{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
Fixes #92 (I think)
This might need some discussion.
Currently CI will run all the versions that the develop version of MDAnalysis will support.
This will cause failures when it attempts to run a brand new version of Python that the last release of MDA doesn't support (for example Python 3.12 + MDAnalysis 2.6.1).
There are two options I can see out of this:
1. We just don't run the latest version of Python against the last release of MDAnalysis - this fix does this.
2. We split up the test step into two, a latest & development step. On the latest step we take the output of mdanalysis-compatible-python with the latest version of MDA, and the development the same python matrix as what we call currently.
- Note: This will need a bit of work to grab out the latest version of MDA, it's not the …
=> Don't run CI on mdanalysis latest + latest python

{{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
I'm not sure why CI was still green after that one 🙀
=> pypi_check shouldn't call setup.py - switch to pipx run build

AUTHORS.md, CHANGELOG.md, tests/test_output.py, {{cookiecutter.repo_name}}/pyproject.toml, {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/__init__.py
Fixes #113
- Changed pyproject.toml to use packagename instead of reponame for tests
- Added setuptools directive to fix installation issue
I used a repo which contains multiple packages as a model for these changes: https://github.com/Gallopsled/pwntools
The idea is that if the repo name differs from the package name, you should be able to do 
```
pip show <repo_name> 
```
But not be able to import the package using the reponame. You must import using
```
import <package_name>
```
However, this leaves the issue of versioning, since the package_name's `__init__` method uses (AFAIK) the version is associated with the repo_name. I set the package's version to use the version associated with repo_name by default and the user will have to be responsible for …
=> [WIP] ModuleNotFound Error Fix

.github/actions/run-cookie-ci/action.yaml, .github/workflows/gh-ci.yaml, CHANGELOG.md, tests/test_output.py, {{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
Relates to #112 
- 
PR Checklist
------------
=> Run all cookie tests and fix check for sdist tarball

.github/actions/run-cookie-ci/action.yaml
Fixes #125 
- Jobs are now manually specified in CI to avoid caching errors.
PR Checklist
------------
=> Fix pylint?

{{cookiecutter.repo_name}}/.github/workflows/{{cookiecutter._ci_name}}.yaml
This seems to be forcing some kind of x86 compatibility build of Python on osx-arm64, removing makes the action pick up the right installer.
You can see this action for more details: https://github.com/MDAnalysis/mdahole2/actions/runs/10024096447/job/27705759572
=> Remove x86 pin setup-miniconda
